#!/bin/bash
LIST=`pacman -Qi | grep "Installed Size" | awk '{print $4}' | paste -sd+ | bc`
SIZE=`echo "scale=2;$LIST / 1000" | bc`
PNUM=`pacman -Q | wc -l` 
echo "Installed: ${SIZE}MB in ${PNUM} packages"


